Dependency handling with venv
aidotse/fleet-learning pull request #30
Opened 2023-08-23 13:11 UTC by obrask1

- Remove conda installation files
- Add venv environment installation with Make
- Update Readme

2023-08-24 06:49 UTC, jonasandersson10 requested changes
Nice work Oscar. There are some things we need to fix before merging. Primarily, if we want to package the project as python package with this installation logic, I think we need to put everything into source a folder with the package name. This probably means we need to update all our imports. 

I've created another branch in which I've started to do some updates and add a python project build CI pipeline. My goal is to include the pytests as well there to make sure everything works. Once that's done we can merge that branch into this one :)

2023-08-24 06:49 UTC, jonasandersson10 commented on pyproject.toml
> +# To keep in sync with the project version specified in vccfl/__version__.py
```suggestion
# To keep in sync with the project version specified in fleetlearning/__version__.py
```

2023-08-24 07:32 UTC, obrask1 commented
> Nice work @obrask1. There are some things we need to fix before merging. Primarily, if we want to package the project as a python package with this installation logic, I think we need to move everything in `src` into a single folder with the package name. Right now I think we install multiple python-modules. Once we updated that, it probably means that we also need to update all our imports.
> 
> I've created another branch in which I've started to do some updates and add a python project build CI pipeline. My goal is to include the pytests as well there to make sure everything works. Once that's done we can merge that branch into this one :)

Great idea! Then I'll keep this PR as WIP until #32 is merged

2023-08-25 07:51 UTC, jonasandersson10 commented
@obrask1 All checks pass again now. Since we've merged my PR already, I think we are done with this or? What do you say?

2023-08-25 08:02 UTC, obrask1 commented
> @obrask1 All checks pass again now. Since we've merged my PR already, I think we are done with this or? What do you say?

agree!!

2023-08-25 08:06 UTC, jonasandersson10 approved these changes
🚀

2023-08-25 08:16 UTC, merged